ifndef SVC_PKTIFS_MAKEFILE
SVC_PKTIFS_MAKEFILE=1
MYDIR:=$(abspath $(dir $(lastword $(MAKEFILE_LIST))))


#SOURCEFILES+=$(addprefix $(MYDIR)/, some_source_file.with_extention)
INCLUDEPATH+=$(MYDIR)
SOURCEPATH+=$(MYDIR)
MODULES+=$(MYDIR)/Makefile


#include $(DEVROOT)/svc/pktifs/Makefile


ifndef INCLUDED
# Included make!

else
# Normal make!

endif

endif


