ifndef SVC_MUDEM_MAKEFILE
SVC_MUDEM_MAKEFILE=1
MYDIR:=$(abspath $(dir $(lastword $(MAKEFILE_LIST))))


SOURCEFILES+=$(addprefix $(MYDIR)/, mudem.c)
INCLUDEPATH+=$(MYDIR)
SOURCEPATH+=$(MYDIR)
MODULES+=$(MYDIR)/Makefile


ifndef INCLUDED
# Included make!

else
# Normal make!

endif

endif


